### ISSUE TITLE
YAMLSemanticError when parsing YAML with curly braces

### ISSUE THREAD

**Issue by leedm777** [eemeli/yaml#114]
YAML such as the following generates an error `YAMLSemanticError: Insufficient indentation in flow collection`

```yaml
foo: {
  bar: boom
}
```

```
> const yaml = require('yaml')
undefined
> yaml.parse('foo: {\n  bar: boom\n}\n', { prettyErrors: true })
{ YAMLSemanticError: Insufficient indentation in flow collection
    at FlowCollection.parse (/Users/dlee/prj/sangoma/zulu/zulu-cloud/node_modules/yaml/dist/cst/FlowCollection.js:77:60)
    at ParseContext._defineProperty (/Users/dlee/prj/sangoma/zulu/zulu-cloud/node_modules/yaml/dist/cst/ParseContext.js:141:25)
    at CollectionItem.parse (/Users/dlee/prj/sangoma/zulu/zulu-cloud/node_modules/yaml/dist/cst/CollectionItem.js:81:19)
    at ParseContext._defineProperty (/Users/dlee/prj/sangoma/zulu/zulu-cloud/node_modules/yaml/dist/cst/ParseContext.js:141:25)
    at Collection.parse (/Users/dlee/prj/sangoma/zulu/zulu-cloud/node_modules/yaml/dist/cst/Collection.js:199:20)
    at ParseContext._defineProperty (/Users/dlee/prj/sangoma/zulu/zulu-cloud/node_modules/yaml/dist/cst/ParseContext.js:157:29)
    at Document.parseContents (/Users/dlee/prj/sangoma/zulu/zulu-cloud/node_modules/yaml/dist/cst/Document.js:176:26)
    at Document.parse (/Users/dlee/prj/sangoma/zulu/zulu-cloud/node_modules/yaml/dist/cst/Document.js:238:19)
    at parse (/Users/dlee/prj/sangoma/zulu/zulu-cloud/node_modules/yaml/dist/cst/parse.js:33:18)
    at parseDocument (/Users/dlee/prj/sangoma/zulu/zulu-cloud/node_modules/yaml/dist/index.js:65:34)
  name: 'YAMLSemanticError',
  message: 'Insufficient indentation in flow collection',
  nodeType: 'FLOW_MAP',
  range: Range { start: 5, end: 20 },
  linePos: { start: { line: 1, col: 6 }, end: { line: 3, col: 2 } } }
```

**Comment by eemeli** [comment]
Duplicate of #113, see there for conclusion.
