### ISSUE TITLE
Your test suite must contain at least one test

### ISSUE THREAD

**Issue by imamol** [eemeli/yaml#175]
- node -v: 12.16.1
 - npm -v: 6.14.5

I am getting below error when I try to `npm test` on v1.10.0
 
bash-4.2# npm test

> yaml@1.10.0 test /wkc-test-fails/yaml
> jest

 PASS  tests/cst/corner-cases.js
 PASS  tests/doc/comments.js
 PASS  tests/doc/types.js
 PASS  tests/doc/parse.js
 PASS  tests/doc/YAML-1.2.spec.js
 PASS  tests/doc/stringify.js
 PASS  tests/doc/errors.js
 PASS  tests/doc/anchors.js
 PASS  tests/doc/foldFlowLines.js
 PASS  tests/doc/collection-access.js
 PASS  tests/doc/createNode.js
 PASS  tests/properties.js
 PASS  tests/doc/YAML-1.1.spec.js
 PASS  tests/cst/YAML-1.2.spec.js
 PASS  tests/cst/parse.js
 PASS  tests/cst/source-utils.js
 PASS  tests/cst/set-value.js
 PASS  tests/cst/Node.js
 FAIL  tests/yaml-test-suite.js
  ● Test suite failed to run

    Your test suite must contain at least one test.

      at onResult (node_modules/@jest/core/build/TestScheduler.js:173:18)
          at async Promise.all (index 18)
      at async TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:271:11)
      at async runJest (node_modules/@jest/core/build/runJest.js:372:19)
      at async _run (node_modules/@jest/core/build/cli/index.js:364:7)
      at async runCLI (node_modules/@jest/core/build/cli/index.js:219:3)

Test Suites: 1 failed, 18 passed, 19 total
Tests:       10 skipped, 720 passed, 730 total

Any idea about this?

**Comment by eemeli** [comment]
Some of the tests are in a git submodule. Run this to get it set up:
```
git submodule update --init
```

**Comment by imamol** [comment]
@eemeli Thanks! Resolved!
