### ISSUE TITLE
onError is not a function when using json schema

### ISSUE THREAD

**Issue by easbar** [eemeli/yaml#238]
Using 2.0.0-3 this code:

```typescript
const doc = YAML.parseDocument('abc', {
    schema: "json"
});
console.log(doc.errors);
```

yields:

```
[
TypeError: onError is not a function
at resolve (yaml/src/tags/json.js:62:7)
at resolveScalar (yaml/src/resolve/resolveScalar.js:6:17)
at resolveNodeValue (yaml/src/resolve/resolveNode.js:100:12)
at resolveNode (yaml/src/resolve/resolveNode.js:131:15)
at parseContents (yaml/src/doc/parseContents.js:18:19)
at Document.parse (yaml/src/doc/Document.js:231:5)
at new Document (yaml/src/doc/Document.js:60:12)
at Object.parseDocument (yaml/src/index.js:25:15)
at Object.<anonymous> (yaml/tests/gh/test.js:6:22)
  at Object.asyncJestTest (yaml/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:106:37) {
    source: PlainValue {
    error: null,
    range: [Range],
    valueRange: [Range],
    props: [],
    type: 'PLAIN',
    value: null,
    resolved: null
  }
  }
]
```

It looks like the `resolve` call in `resolveScalar.js` is failing to pass the `onError` argument.

With current master (1a30027250b655267affe56be34e99a300273eca) the output seems correct:

```
     YAMLParseError: Unresolved plain scalar "abc"
```

**Comment by eemeli** [comment]
Yeah, the whole of `yaml/src/resolve/...` effectively got rewritten, and I recall noticing & fixing this particular issue.

**Comment by easbar** [comment]
Ok, and would it be a lot of effort to backport the fix to 2.0.0-3? And can you comment on the state of the new parser? Is it close to replace the old one? I'd be willing to keep experimenting with the new parser.

**Comment by eemeli** [comment]
I'm expecting to get 2.0.0-4 out within a week or two. The new parser is pretty much ready & it's replaced the old one in the master branch. There are a couple of other changes that I've still got intended for it, plus of course a documentation update.

**Comment by easbar** [comment]
Ok awesome :) I will use master then and report issues I run into if I may.
