### ISSUE TITLE
[v2.0.0-x] Error: Failed to resolve repeated object (this should not happen)

### ISSUE THREAD

**Issue by MikeRalphson** [eemeli/yaml#287]
**Describe the bug**

When stringifying an object containing multiple references to the same object which have been serialised as strings, the anchor mechanism seems to get confused.

**To Reproduce**

```js
const yaml = require('yaml');

const o = {};

const d = new Date();

o.d1 = d;
o.d2 = d;

console.log(yaml.stringify(o));
```

```js
/Users/mikeralphson/node/oad/node_modules/yaml/dist/doc/anchors.js:67
                    throw error;
                    ^

Error: Failed to resolve repeated object (this should not happen)
    at setAnchors (/Users/mikeralphson/node/oad/node_modules/yaml/dist/doc/anchors.js:64:35)
    at Document.createNode (/Users/mikeralphson/node/oad/node_modules/yaml/dist/doc/Document.js:110:9)
    at new Document (/Users/mikeralphson/node/oad/node_modules/yaml/dist/doc/Document.js:50:34)
    at Object.stringify (/Users/mikeralphson/node/oad/node_modules/yaml/dist/public-api.js:100:12)
    at Object.<anonymous> (/Users/mikeralphson/node/oad/bin/testyd.js:10:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  source: 2021-06-17T10:49:08.525Z,
  ref: { anchor: 'a1', node: null }
}
```

**Expected behaviour**

`yaml.stringify` should not throw an Error.

**Versions (please complete the following information):**

- Environment: Node.js 14.16.0
- `yaml`: 2.0.0-6

**Additional context**

`yaml` 1.x stringifies this as two strings without an anchor.

**Comment by eemeli** [comment]
Good catch! There was an early return when creating scalars that didn't take this into account. Should be fixed now.
