### ISSUE TITLE
Document#setIn() throws errors for paths that do not already exist

### ISSUE THREAD

**Issue by keawade** [eemeli/yaml#345]
**Describe the bug**

I am getting errors when I attempt to call `Document#setIn` with a path that does not already exist.

**To Reproduce**

```yaml
# test.yaml

hello: there
```

```js
// test01.js

const fs = require("fs");
const yaml = require("yaml");

const file = fs.readFileSync("test.yaml", "utf-8");

const doc = yaml.parseDocument(file);
doc.setIn(["foo", "bar"], "baz");

console.log(doc.toString());
```

I am get this output from `node test01.js`:

```
/home/keawade/Code/scratchpad/node_modules/yaml/dist/resolveSeq-d03cb037.js:124
      if (node instanceof Collection) node.setIn(rest, value);else if (node === undefined && this.schema) this.set(key, collectionFromPath(this.schema, rest, value));else throw new Error(`Expected YAML collection at ${key}. Remaining path: ${rest}`);
                                                                                                                                                                           ^

Error: Expected YAML collection at foo. Remaining path: bar
    at YAMLMap.setIn (/home/keawade/Code/scratchpad/node_modules/yaml/dist/resolveSeq-d03cb037.js:124:178)
    at Document.setIn (/home/keawade/Code/scratchpad/node_modules/yaml/dist/Document-9b4560a1.js:574:21)
    at Object.<anonymous> (/home/keawade/Code/scratchpad/yaml-stuff/test01.js:9:5)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
```

If I change my yaml file to instead be empty:

```yaml
# test.yaml
```

then I get this output:

```
/home/keawade/Code/scratchpad/node_modules/yaml/dist/Document-9b4560a1.js:500
  throw new Error('Expected a YAML collection as document contents');
  ^

Error: Expected a YAML collection as document contents
    at assertCollection (/home/keawade/Code/scratchpad/node_modules/yaml/dist/Document-9b4560a1.js:500:9)
    at Document.setIn (/home/keawade/Code/scratchpad/node_modules/yaml/dist/Document-9b4560a1.js:573:7)
    at Object.<anonymous> (/home/keawade/Code/scratchpad/yaml-stuff/test01.js:9:5)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
```

**Expected behaviour**

Judging by [the documentation here](https://eemeli.org/yaml/v1/#collections) I would expect `setIn` to work with this set up:

> If any of the intermediate collections is not found:
>
> - getIn and hasIn will return undefined or false (respectively)
> - **addIn and setIn will create missing collections;** non-negative integer keys will create sequences, all other keys create maps
> - deleteIn will throw an error

**Versions (please complete the following information):**

- Environment: Node.js 14.18.2
- `yaml`: Uncertain. Using default configuration of the library.

**Additional context**

This looks like it may be related to #174. I tried to use [the suggested work around from that thread](https://github.com/eemeli/yaml/issues/174#issuecomment-632281283) but it did not resolve the issue for me.

This set up works if the path already exists:

```yaml
# test.yaml

foo:
  bar: howdy
```

**Comment by eemeli** [comment]
It looks like this is indeed a bg in `yaml@1`, but it works as intended on the actively developed version, which is available on npm as `yaml@next`.

A PR for fixing this on the [`v1` branch](https://github.com/eemeli/yaml/tree/v1) would be welcome, but I'd recommend switching to a `v2` prerelease version, if possible.

**Comment by keawade** [comment]
Ah, I see. Yep, updating to `@next` resolved the issue.

Do you have an idea of when `@next` will become stable?
