### ISSUE TITLE
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './types' is not defined by "exports" after updating to npm i 2.0.0-11

### ISSUE THREAD

**Issue by jacek-jablonski** [eemeli/yaml#373]
**Describe the bug**
Error 
```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './types' is not defined by "exports"
```
started to appear after upgrading yaml to 2.0.0-11

**To Reproduce**
`npm install yaml@2.0.0-11`

```
const { Pair } = require("yaml/types");
```

**Expected behaviour**
2.0.0-11 should be backwards compatible with 2.0.0-10.

**Versions (please complete the following information):**

- Environment: Node 16.12.0
- `yaml`: 2.0.0-11

**Comment by jacek-jablonski** [comment]
Sorry, seems like my mistake.

**Comment by zvictor** [comment]
I am facing the same issue being thrown by `aws-cdk`

```haskell
Error: Package subpath './types' is not defined by "exports" in /Users/zvictor/development/divino.ai/node_modules/.pnpm/node_modules/yaml/package.json

Trace: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './types' is not defined by "exports" in /Users/zvictor/development/divino.ai/node_modules/.pnpm/node_modules/yaml/package.json
    at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
    at new NodeError (node:internal/errors:399:5)
    at exportsNotFound (node:internal/modules/esm/resolve:266:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:602:9)
    at resolveExports (node:internal/modules/cjs/loader:550:36)
    at Module._findPath (node:internal/modules/cjs/loader:619:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1046:27)
    at Module._load (node:internal/modules/cjs/loader:905:27)
    at Module.require (node:internal/modules/cjs/loader:1127:19)
    at require (node:internal/modules/helpers:112:18)
    at Object.<anonymous> (/Users/zvictor/development/divino.ai/node_modules/.pnpm/aws-cdk@2.62.2/node_modules/aws-cdk/lib/util/yaml-cfn.ts:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1246:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1300:10)
    at Module.load (node:internal/modules/cjs/loader:1103:32)
    at Module._load (node:internal/modules/cjs/loader:942:12)
    at Module.require (node:internal/modules/cjs/loader:1127:19)
    at require (node:internal/modules/helpers:112:18)
    at Object.<anonymous> (/Users/zvictor/development/divino.ai/node_modules/.pnpm/aws-cdk@2.62.2/node_modules/aws-cdk/lib/serialize.ts:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1246:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1300:10)
    at Module.load (node:internal/modules/cjs/loader:1103:32)
    at Module._load (node:internal/modules/cjs/loader:942:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:168:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at process.<anonymous> (file:///Users/zvictor/development/divino.ai/node_modules/.pnpm/sst@2.0.34/node_modules/sst/cli/sst.js:58:17)
    at process.emit (node:events:524:35)
    at process.processEmit [as emit] (/Users/zvictor/development/divino.ai/node_modules/.pnpm/signal-exit@3.0.7/node_modules/signal-exit/index.js:199:34)
    at process._fatalException (node:internal/process/execution:159:25)
    at processPromiseRejections (node:internal/process/promises:289:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
```

**Comment by zvictor** [comment]
Looks like this is the root issue: https://github.com/aws/aws-cdk/issues/23182
