### ISSUE TITLE
Cannot find module 'yaml'

### ISSUE THREAD

**Issue by LaXiS96** [eemeli/yaml#387]
**Describe the bug**

`MODULE_NOT_FOUND` when using `require('yaml')` on latest Node.js LTS in a fresh project initialized with modern Yarn.

`yaml` should be found the same as other installed packages (like `nunjucks`) which are working as expected.
`.pnp.cjs` contains one packageLocation reference to `./.yarn/cache/yaml-npm-2.0.1-92722db385-23f95ff0d6.zip/node_modules/yaml/` and `.yarn/cache` contains `yaml-npm-2.0.1-92722db385-23f95ff0d6.zip` so the package is indeed installed.

The main difference I noticed is that `nunjucks` has an `index.js` in `node_modules/nunjucks/`, while `yaml` has none (in `node_modules/yaml/`).
I am not familiar enough with Node.js internals to know if `index.js` is expected to exist in the package root or if Node.js is supposed to follow `main` from `package.json`.

**To Reproduce**

`test.js`:
```
const yaml = require('yaml');
```

Command line:
```
PS C:\Users\me\project> yarn add yaml
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed                                                                                                                                                                                  
➤ YN0000: ┌ Fetch step
➤ YN0013: │ yaml@npm:2.0.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed
➤ YN0000: Done in 0s 96ms
PS C:\Users\me\project> node .\test.js
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'yaml'
Require stack:
- C:\Users\me\project\test.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\me\project\test.js:1:14)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'C:\\Users\\me\\project\\test.js' ]
}
```

**Expected behaviour**

See above

**Versions (please complete the following information):**

- Node.js 16.15.0
- Yarn 3.2.0
- `yaml`: 2.0.1

**Additional context**

None

**Comment by eemeli** [comment]
Could you provide in your reproduction the steps that you are using to first install `yaml`? As is, what you've provided is not enough to replicate the issue.

**Comment by LaXiS96** [comment]
Sure, here is a full transcript of the commands I used to create a new project from scratch and without any customization:
```
PS C:\Users\me> mkdir test
PS C:\Users\me> cd .\test\
PS C:\Users\me\test> yarn init -2
{
  name: 'test',
  packageManager: 'yarn@3.2.0'
}
PS C:\Users\me\test> yarn add yaml
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0013: │ yaml@npm:2.0.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed in 0s 916ms
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed
➤ YN0000: Done in 0s 991ms
PS C:\Users\me\test> node .\test.js
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'yaml'
Require stack:
- C:\Users\me\test\test.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\me\test\test.js:1:14)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'C:\\Users\\me\\test\\test.js' ]
}
```

`test.js` contains only:
```
const yaml = require('yaml');
```

This was run on a different machine and the result is the same. (Node.js is also v16.15.0)

**Comment by LaXiS96** [comment]
Oh well, that was it. I guess they could have put that notice in the getting started page since it's not an obvious change, and Plug'n'Play is now the recommended setup...

Thank you for your time
