### ISSUE TITLE
Syntax error in composer.js

### ISSUE THREAD

**Issue by scott-parkhill** [eemeli/yaml#466]
**Describe the bug**
Syntax error in the script according to my machine. This occurs just typing in `npx postcss`.

**Versions (please complete the following information):**

- Environment: Ubuntu 22.04
- yaml: 2.2.1

```
"devDependencies": {
    "autoprefixer": "10.4.14",
    "postcss": "8.4.21",
    "postcss-cli": "10.1.0",
    "sass": "1.59.3"
  },
```

**Additional context**
```
npx postcss /home/project/wwwroot/css/compiled/main.css --no-map --use autoprefixer --output /home/project/wwwroot/css/compiled/main.css
/home/project/node_modules/yaml/dist/compose/composer.js:33
                if (prelude[i + 1]?.[0] !== '#')
                                   ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/project/node_modules/yaml/dist/index.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

**Comment by scott-parkhill** [comment]
Resolved. Issue with node version, not yaml. Was at v12, now at v19.
