### ISSUE TITLE
Failing tests on v2.3.1

### ISSUE THREAD

**Issue by bambuchaAdm** [eemeli/yaml#483]
**Describe the bug**
After checkout library repository i usually run tests to look into baseline. This time i get few errors and it looks like i got few errors.

**To Reproduce**
1. Clone repository
2. `npm install`
3. `npm run test` 

**Outcomes**
```
Summary of all failing tests
 FAIL  tests/json-test-suite.ts
  ● Test suite failed to run

    ENOENT: no such file or directory, scandir '/home/bambucha/lab/yaml/tests/json-test-suite/test_parsing'

      52 | describe('json-test-suite test_parsing', () => {
      53 |   const dir = resolve(__dirname, 'json-test-suite', 'test_parsing')
    > 54 |   for (const fn of readdirSync(dir)) {
         |                               ^
      55 |     if (!fn.endsWith('.json')) continue
      56 |     const name = basename(fn, '.json')
      57 |     const src = readFileSync(resolve(dir, fn), 'utf8')

      at tests/json-test-suite.ts:54:31
      at Object.describe (tests/json-test-suite.ts:52:1)

 FAIL  tests/yaml-test-suite.ts
  ● Test suite failed to run

    Your test suite must contain at least one test.

      at onResult (node_modules/@jest/core/build/TestScheduler.js:133:18)
      at node_modules/@jest/core/build/TestScheduler.js:254:19
      at node_modules/emittery/index.js:363:13
          at Array.map (<anonymous>)
      at Emittery.emit (node_modules/emittery/index.js:361:23)


Test Suites: 2 failed, 22 passed, 24 total
Tests:       975 passed, 975 total
Snapshots:   0 total
Time:        3.614 s, estimated 4 s
```

**Expected behaviour**
Green tests 

**Versions (please complete the following information):**

- Environment 1: Node v18.16.1 with npm 9.5.1
- Environment 2: Node v16.10.0 with npm 7.24.0
- `yaml`: v2.3.1 tag

**Additional context**

**Comment by eemeli** [comment]
See https://github.com/eemeli/yaml/blob/main/docs/CONTRIBUTING.md#getting-started
