### ISSUE TITLE
Missing error on parsed document for unresolved alias

### ISSUE THREAD

**Issue by stefreak** [eemeli/yaml#497]
**Describe the bug**
When parsing a document like this:
```yaml
foo: *bar
```

The `errors` array on the parsed document is empty, and `toJS` will throw `ReferenceError: Unresolved alias`

**To Reproduce**
```repl
> const yaml = await import("yaml")
undefined
> const docs = yaml.parseAllDocuments("foo: *bar")
undefined
> docs.length
1
> docs[0].errors
[]
> docs[0].toJS()
Uncaught ReferenceError: Unresolved alias (the anchor must be set before the alias): bar
    at Alias.toJSON (/Users/steffen/work/github/garden/core/node_modules/yaml/dist/nodes/Alias.js:42:19)
    at Object.toJS (/Users/steffen/work/github/garden/core/node_modules/yaml/dist/nodes/toJS.js:22:26)
    at Object.addPairToJSMap (/Users/steffen/work/github/garden/core/node_modules/yaml/dist/nodes/addPairToJSMap.js:32:34)
    at YAMLMap.toJSON (/Users/steffen/work/github/garden/core/node_modules/yaml/dist/nodes/YAMLMap.js:124:28)
    at Object.toJS (/Users/steffen/work/github/garden/core/node_modules/yaml/dist/nodes/toJS.js:22:26)
    at Document.toJS (/Users/steffen/work/github/garden/core/node_modules/yaml/dist/doc/Document.js:301:26)
>
```

**Expected behaviour**
I expect an error on the document after calling `yaml.parseAllDocuments`.

```repl
> docs[0].errors.length
1
```

**Versions (please complete the following information):**

- Environment: Node.js v18.15.0
- `yaml`: 2.3.2

**Comment by eemeli** [comment]
That's a fair concern. A method for discovering unresolved aliases should be provided, and a parsing option to include errors for them.

**Comment by eemeli** [comment]
Pondering now whether something actually needs to be added, as this works, and provides an opportunity to take whatever locally appropriate action when encountering an unresolvable alias.
```js
import { parseDocument, visit } from 'yaml'

const doc = parseDocument('foo: *bar');
visit(doc, {
  Alias(key, node) {
    if (!node.resolve(doc)) throw new Error(`Unresolved alias: ${node}`)
  }
});
```

**Comment by eemeli** [comment]
Closing, as the approach in the preceding comment should fulfill the user need, as seen e.g. [here](https://github.com/msivasubramaniaan/yaml-language-server/blob/4a5c6ca04f5700ac567007d0fa37a1482ad87ca0/src/languageservice/services/validation/unused-anchors.ts#L31-L35).
