### ISSUE TITLE
Custom map types

### ISSUE THREAD

**Issue by isaacs** [eemeli/yaml#89]
Is there a good example for how to go about adding a custom object/map type?

I'd like to have custom handling for `Error` objects.  They're basically normal objects, but their `name`, `message`, and `stack` properties (which are pretty important!) are typically not enumerable.  I figured I could take a look at the `!!set` and `!!omap` implementations, but they're a bit tangled with the internals.

One API approach might be to allow the `stringify` method to return an object of key/value pairs instead of a string.  (Sort of like how the JSON.stringify replacer function does.)

Something like this:

```js
const { restringify } = require('yaml/schema')

module.exports = {
  identify: value => value instanceof Error,
  tag: '!error',
  resolve (doc, cst) {
    const obj = cst.value
    const er = new Error(obj.message)
    er.name = obj.name
    er.stack = obj.stack
    for (let i in obj) {
      er[i] = obj[i]
    }
    return er
  },
  stringify (item, ctx, onComment, onChompKeep) {
    // constitute an object that YAML knows how to stringify, just a plain old javascript object
    const er = item.value
    const value = {
      name: er.name,
      message: er.message,
      stack: er.stack,
      ...er
    }
    return restringify({ value }, ctx, onComment, onChompKeep)
  }
}
```

Then the resulting yaml from `{ er: new Error('foo') }` would be something like:

```yaml
er:
  !error
  name: 'Error'
  message: 'foo'
```

**Comment by isaacs** [comment]
Here's what I've got so far, which seems to mostly work, but blows up if the error has a field with a circular reference: https://gist.github.com/isaacs/c5358fedf391f57fa85b9ca45d3a1a3e  (Unfortunately a lot of assertion libs get into this state pretty easily, since they attach all sorts of junk onto the error object that they throw.)

**Comment by isaacs** [comment]
Stack trace stringifying an error like:

```js
obj = { er: new Error('foo') }
obj.er.o = {}
obj.er.o.o = o
yaml.stringify(obj)
```

```
    ... repeats the last few lines ...
    at Array.map (<anonymous>)
    at Object.createMap [as createNode] (/Users/isaacs/dev/js/tap-yaml/node_modules/yaml/dist/schema/failsafe.js:32:34)
    at Schema.createNode (/Users/isaacs/dev/js/tap-yaml/node_modules/yaml/dist/schema/index.js:114:43)
    at map.items.Object.keys.map.key (/Users/isaacs/dev/js/tap-yaml/node_modules/yaml/dist/schema/failsafe.js:34:24)
    at Array.map (<anonymous>)
    at Object.createMap [as createNode] (/Users/isaacs/dev/js/tap-yaml/node_modules/yaml/dist/schema/failsafe.js:32:34)
    at Schema.createNode (/Users/isaacs/dev/js/tap-yaml/node_modules/yaml/dist/schema/index.js:114:43)
    at map.items.Object.keys.map.key (/Users/isaacs/dev/js/tap-yaml/node_modules/yaml/dist/schema/failsafe.js:34:24)
    at Array.map (<anonymous>)
    at Object.createMap [as createNode] (/Users/isaacs/dev/js/tap-yaml/node_modules/yaml/dist/schema/failsafe.js:32:34)
    at Schema.createNode (/Users/isaacs/dev/js/tap-yaml/node_modules/yaml/dist/schema/index.js:114:43)
    at Pair.toString (/Users/isaacs/dev/js/tap-yaml/node_modules/yaml/dist/schema/Pair.js:106:26)
    at Schema.stringify (/Users/isaacs/dev/js/tap-yaml/node_modules/yaml/dist/schema/index.js:270:52)
    at nodes.items.reduce (/Users/isaacs/dev/js/tap-yaml/node_modules/yaml/dist/schema/Collection.js:119:28)
    at Array.reduce (<anonymous>)
    at YAMLError.toString (/Users/isaacs/dev/js/tap-yaml/node_modules/yaml/dist/schema/Collection.js:100:30)
    at YAMLError.toString (/Users/isaacs/dev/js/tap-yaml/node_modules/yaml/dist/schema/Map.js:151:18)
    at stringify (/Users/isaacs/dev/js/tap-yaml/lib/types/error.js:41:9)
    at Schema.stringify (/Users/isaacs/dev/js/tap-yaml/node_modules/yaml/dist/schema/index.js:274:57)
    at Pair.toString (/Users/isaacs/dev/js/tap-yaml/node_modules/yaml/dist/schema/Pair.js:111:33)
    at Schema.stringify (/Users/isaacs/dev/js/tap-yaml/node_modules/yaml/dist/schema/index.js:270:52)
    at nodes.items.reduce (/Users/isaacs/dev/js/tap-yaml/node_modules/yaml/dist/schema/Collection.js:119:28)
    at Array.reduce (<anonymous>)
    at YAMLMap.toString (/Users/isaacs/dev/js/tap-yaml/node_modules/yaml/dist/schema/Collection.js:100:30)
    at YAMLMap.toString (/Users/isaacs/dev/js/tap-yaml/node_modules/yaml/dist/schema/Map.js:151:18)
    at stringify (/Users/isaacs/dev/js/tap-yaml/node_modules/yaml/dist/schema/failsafe.js:61:60)
    at Schema.stringify (/Users/isaacs/dev/js/tap-yaml/node_modules/yaml/dist/schema/index.js:274:57)
    at Document.toString (/Users/isaacs/dev/js/tap-yaml/node_modules/yaml/dist/Document.js:597:32)
    at String (<anonymous>)
    at Object.stringify (/Users/isaacs/dev/js/tap-yaml/node_modules/yaml/dist/index.js:74:10)
    at Object.module.exports.obj [as stringify] (/Users/isaacs/dev/js/tap-yaml/lib/stringify.js:4:30)
    at Object.<anonymous> (/Users/isaacs/dev/js/tap-yaml/er.js:28:23)
```

It's a bit different if I have an object like this:

```js
const obj = { error: new Error('foo') }
obj.error.root = obj
```

```
    ... repeats ...
    at YAMLMap.toString (/Users/isaacs/dev/js/tap-yaml/node_modules/yaml/dist/schema/Collection.js:100:30)
    at YAMLMap.toString (/Users/isaacs/dev/js/tap-yaml/node_modules/yaml/dist/schema/Map.js:151:18)
    at stringify (/Users/isaacs/dev/js/tap-yaml/node_modules/yaml/dist/schema/failsafe.js:61:60)
    at Schema.stringify (/Users/isaacs/dev/js/tap-yaml/node_modules/yaml/dist/schema/index.js:274:57)
    at Pair.toString (/Users/isaacs/dev/js/tap-yaml/node_modules/yaml/dist/schema/Pair.js:111:33)
    at Schema.stringify (/Users/isaacs/dev/js/tap-yaml/node_modules/yaml/dist/schema/index.js:270:52)
    at nodes.items.reduce (/Users/isaacs/dev/js/tap-yaml/node_modules/yaml/dist/schema/Collection.js:119:28)
    at Array.reduce (<anonymous>)
    at YAMLError.toString (/Users/isaacs/dev/js/tap-yaml/node_modules/yaml/dist/schema/Collection.js:100:30)
    at YAMLError.toString (/Users/isaacs/dev/js/tap-yaml/node_modules/yaml/dist/schema/Map.js:151:18)
    at stringify (/Users/isaacs/dev/js/tap-yaml/lib/types/error.js:41:9)
    at Schema.stringify (/Users/isaacs/dev/js/tap-yaml/node_modules/yaml/dist/schema/index.js:274:57)
    at Pair.toString (/Users/isaacs/dev/js/tap-yaml/node_modules/yaml/dist/schema/Pair.js:111:33)
    at Schema.stringify (/Users/isaacs/dev/js/tap-yaml/node_modules/yaml/dist/schema/index.js:270:52)
    at nodes.items.reduce (/Users/isaacs/dev/js/tap-yaml/node_modules/yaml/dist/schema/Collection.js:119:28)
    at Array.reduce (<anonymous>)
    at YAMLMap.toString (/Users/isaacs/dev/js/tap-yaml/node_modules/yaml/dist/schema/Collection.js:100:30)
    at YAMLMap.toString (/Users/isaacs/dev/js/tap-yaml/node_modules/yaml/dist/schema/Map.js:151:18)
    at stringify (/Users/isaacs/dev/js/tap-yaml/node_modules/yaml/dist/schema/failsafe.js:61:60)
    at Schema.stringify (/Users/isaacs/dev/js/tap-yaml/node_modules/yaml/dist/schema/index.js:274:57)
    at Document.toString (/Users/isaacs/dev/js/tap-yaml/node_modules/yaml/dist/Document.js:597:32)
    at String (<anonymous>)
    at Object.stringify (/Users/isaacs/dev/js/tap-yaml/node_modules/yaml/dist/index.js:74:10)
    at Object.module.exports.obj [as stringify] (/Users/isaacs/dev/js/tap-yaml/lib/stringify.js:4:30)
    at Object.<anonymous> (/Users/isaacs/dev/js/tap-yaml/er.js:30:23)
```

**Comment by isaacs** [comment]
Aha!  Got it working with this latest change: https://gist.github.com/isaacs/c5358fedf391f57fa85b9ca45d3a1a3e/revisions

The key was to use `schema.createNode(key, ctx.wrapScalars, null, ctx)` to create the key and value, and then `ernode.items.push(new Pair(k, v))`, instead of `errnode.add({key, value})`.

I think this area definitely could use a bit of polish and documentation, though :)

**Comment by eemeli** [comment]
Apologies and thank you for being a guinea pig for custom type development. Out of the existing custom collections, `!!pairs` might have the fewest implementation-specific details to figure out. On the other hand, it gets away with not extending the `YAMLMap` or `YAMLSeq` classes which you do need for the custom `toJSON()` method.

I should figure out proper exports for all the internals that are required to implement custom types, including custom collections. The `yaml/dist/...` endpoints aren't really part of the public API, so I won't guarantee that they won't change between minor releases. Also, using those probably won't work right in browser environments. Unfortunately, that's the only alternative for custom collections atm.

Dealing with circular references is indeed rather tricky, but it should be automatic if you're only considering `YAML.stringify()` usage and you call `schema.createNode` to wrap the keys & values (as you already do).

**Comment by isaacs** [comment]
By way of sketching out an idea, how do you feel about an API something like this?

```js
const errorTag = {
  tag: '!error',
  identify: er => er instanceof Error,
  resolve: (doc, cst) => {
    // mapValue is parallel to strValue
    // returns the contents of the thing as an object (or map if mapAsMap is true)
    // should raise an error if the value isn't parseable as an map
    // could also have cst.seqValue() which would return an array
    const obj = cst.mapValue({ mapAsMap: false })
    const Cls = obj.name === 'EvalError' ? EvalError
      : obj.name === 'RangeError' ? RangeError
      : obj.name === 'ReferenceError' ? ReferenceError
      : obj.name === 'SyntaxError' ? SyntaxError
      : obj.name === 'TypeError' ? TypeError
      : obj.name === 'URIError' ? URIError
      : Error
    const er = Object.assign(new Cls(obj.message), obj)
    return er
  },
  stringify: (value, ctx, onComment, onChompKeep) => {
    // if it returns a map, JS object, set, or array, then stringify as it would that item,
    // but keeping the '!error' tag in the output
    const obj = {
      name: er.name,
      message: er.message,
      stack: er.stack,
      ...er,
    }
  }
}
```

> The `yaml/dist/...` endpoints aren't really part of the public API, so I won't guarantee that they won't change between minor releases.

Thanks for the caveat.  I'm using my own fork from GitHub, and 100% understand the risks of relying on internals and unsupported APIs.  When the functionality makes its way into some final form, I'll adjust and move over to the "official" release.

> Apologies and thank you for being a guinea pig for custom type development.

No worries!  While this part of the library definitely feels a bit rough, overall I'm finding this library to be pretty well laid out and easy to work with, and moving more of the functionality into the yaml implementation is going to make the next version of node-tap a lot more robust and maintainable.  Thanks for choosing to take on such a big and weird puzzle as this :)

**Comment by eemeli** [comment]
I'm not convinced that adding `mapValue` and/or `seqValue` methods to CST nodes is the right thing to do here. There's a separate transformation/verification stage that's needed to get from CST collections to AST maps & sequences, and that process depends on and to some extent modifies the whole document, rather than just the node in question (e.g. by depending on the schema, and appending errors to `doc.errors`). This is why `parseMap()` and `parseSeq()` also require `doc` as a parameter.

**Comment by isaacs** [comment]
Hm, ok.  Would it be possible to do  something like `const obj = parseMap(cst, doc, { mapAsMap: false })` then?

My goal is just to have custom map/seq types that don't require quite so much involvement with the internals and class structure.

**Comment by eemeli** [comment]
Here's what I've got so far. Following on from #94 I've expanded the public API a bit in the [`re-export` branch](../tree/re-export), and here's a potential implementation of a representation of `Error` in YAML:

```js
const { YAMLMap, Pair } = require("yaml/types");
const { parseMap } = require("yaml/util");

class JavaScriptError extends YAMLMap {
  toJSON(_, ctx) {
    const { name, message, ...rest } = super.toJSON(_, ctx);
    const Cls =
      name === "EvalError"
        ? EvalError
        : name === "RangeError"
        ? RangeError
        : name === "ReferenceError"
        ? ReferenceError
        : name === "SyntaxError"
        ? SyntaxError
        : name === "TypeError"
        ? TypeError
        : name === "URIError"
        ? URIError
        : Error;
    const err = Object.assign(new Cls(message), rest);
    return err;
  }
}

const errorTag = {
  tag: "!error",
  identify: err => err instanceof Error,
  createNode(schema, err, ctx) {
    const node = new JavaScriptError();
    const keys = Object.keys(err);
    if (!keys.includes("name")) keys.push("name");
    if (!keys.includes("message")) keys.push("message");
    if (!keys.includes("stack")) keys.push("stack");
    node.items = keys.map(key => {
      const k = schema.createNode(key, ctx.wrapScalars, null, ctx);
      const v = schema.createNode(err[key], ctx.wrapScalars, null, ctx);
      return new Pair(k, v);
    });
    return node;
  },
  resolve(doc, cst) {
    const map = parseMap(doc, cst);
    return Object.assign(new JavaScriptError(), map);
  },
  stringify: (value, ctx, onComment, onChompKeep) =>
    value.toString(ctx, onComment, onChompKeep)
};
```

Some parts of that are a bit too much copy-paste from internal code, but it's a bit tricky to streamline the process much more. Essentially, there are four conversion stages that need to be considered:
* JS -> Node -> YAML string
* YAML string -> Node -> JS

`YAML.parse()` and `YAML.stringify()` each leap over the middle stage here, but it's still happening in the background, and it's necessary -- there are plenty of document-level details like circular references that need to be accounted for. So, `createNode` is taking care of JS -> Node and Node -> YAML string is handled by the parent YAMLMap; YAML string -> Node is handled by `resolve`, which is pretty bare-bones, and Node -> JS is done by `toJSON`.

**Comment by isaacs** [comment]
@eemeli This is wonderful, and would definitely keep my grubby fingers out of your `dist` folder :)

I'm a bit confused by this part:

```js
  resolve(doc, cst) {
    const map = parseMap(doc, cst);
    return Object.assign(new JavaScriptError(), map);
  },
```

Isn't `resolve` supposed to return an `Error` object in this case?  Will the parser detect that it's a YAML Node and do the right thing with it?

**Comment by eemeli** [comment]
It's perhaps a bit confusingly named, but `resolve()` essentially takes in a CST node, and "resolves" it into an AST node. In this case the JavaScriptError implementation extends YAMLMap, because it has inner fields. E.g. `YAML.parse()` would then immediately call its `.toJSON()` method to turn it into a JS object (and Error in this case), but `YAML.parseDocument()` would not. For instance, if the error contains some data that's present elsewhere in the document, the resolved AST node might represent that with an anchor node. In particular this middle stage is required to represent comments, which may end up practically anywhere in a YAML string.

**Comment by isaacs** [comment]
Thanks, that makes sense. +1 on this API :)

**Comment by eemeli** [comment]
Tinkered a bit more with the API. I updated the example above accordingly. Might be almost happy with it now.

**Comment by eemeli** [comment]
Closing this, as the API & documentation have been updated and will be published with the next release.

**Comment by isaacs** [comment]
Fantastic!  I've been depending on my git fork so far, but I'll add a todo item to review the docs and get back on mainline as soon as the next release is out :)

**Comment by isaacs** [comment]
I'm trying to port to this new API, but I'm finding that the `!error` tag isn't included, even though I'm setting `default: false` on the tag definition object.  Am I missing something? https://gist.github.com/isaacs/42ec587886b54b802104e57495e0348c

**Comment by isaacs** [comment]
Ah, figured it out.  It needs to set a `.tag` property on the node class object.

**Comment by remi00** [comment]
@eemeli I just wanted to say that this issue thread helped me a lot building a new custom tag based on `YAMLMap`. I would find it highly valuable to include such example within official docs (I know v2 could differ in this area though).
